[2022-03-07 19:53:34 +0000] [18570] [INFO] Starting gunicorn 20.1.0
[2022-03-07 19:53:34 +0000] [18570] [INFO] Listening at: http://0.0.0.0:8000 (18570)
[2022-03-07 19:53:34 +0000] [18570] [INFO] Using worker: sync
[2022-03-07 19:53:34 +0000] [18572] [INFO] Booting worker with pid: 18572
[2022-03-07 19:53:34 +0000] [18572] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ncaab.wsgi'
[2022-03-07 19:53:34 +0000] [18572] [INFO] Worker exiting (pid: 18572)
[2022-03-07 19:53:34 +0000] [18570] [INFO] Shutting down: Master
[2022-03-07 19:53:34 +0000] [18570] [INFO] Reason: Worker failed to boot.
